---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oc-test-app-summon-sidecar
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: oc-test-app-summon-sidecar
      containers:
      - image: 172.30.1.1:5000/test-app/webapp:test-app
        imagePullPolicy: Always
        name: test-app
        env:
          - name: CONJUR_APPLIANCE_URL
            value: "https://conjur-follower.conjur.svc.cluster.local/api"
          - name: CONJUR_ACCOUNT
            value: dev
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: test-app
                key: ssl-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_VERSION
            value: "5"
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      - image: cyberark/conjur-kubernetes-authenticator
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_VERSION
            value: '5'
          - name: CONJUR_APPLIANCE_URL
            value: "https://conjur-follower.conjur.svc.cluster.local/api"
          - name: CONJUR_AUTHN_URL
            value: "https://conjur-follower.conjur.svc.cluster.local/api/authn-k8s/dev"
          - name: CONJUR_ACCOUNT
            value: dev
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/dev/apps/test-app/service_account/oc-test-app-summon-sidecar"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: test-app
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
