#!/bin/bash
set -eo pipefail
oc login -u $OSHIFT_CONJUR_ADMIN
./0_check_dependencies.sh
./1_load_conjur_policies.sh
./2_init_conjur_cert_authority.sh
./3_build_and_push_images.sh
./4_deploy_test_app.sh
./5_retrieve_secret.sh
