#!/bin/bash 
set -euo pipefail

. utils.sh

set_namespace default

if [[ $PLATFORM == openshift ]]; then
  oc login -u $OSHIFT_CLUSTER_ADMIN_USERNAME
fi

if has_namespace $TEST_APP_NAMESPACE_NAME; then
  $cli delete namespace $TEST_APP_NAMESPACE_NAME

  printf "Waiting for $TEST_APP_NAMESPACE_NAME namespace deletion to complete"

  while : ; do
    printf "..."
    
    if has_namespace "$TEST_APP_NAMESPACE_NAME"; then
      sleep 5
    else
      break
    fi
  done

  echo ""
fi

set +e
test_sidecar_app_docker_image=$(platform_image test-sidecar-app)
test_init_app_docker_image=$(platform_image test-init-app)
docker rmi $test_sidecar_app_docker_image $test_init_app_docker_image &> /dev/null

echo "Test app environment purged."
