#!/bin/bash
set -euo pipefail

if [[ $PLATFORM == openshift ]]; then
  oc login -u $OSHIFT_CLUSTER_ADMIN_USERNAME
fi

./0_check_dependencies.sh

./stop

./1_prepare_conjur_namespace.sh
./2_prepare_docker_images.sh
./3_deploy_conjur_followers.sh
./4_configure_followers.sh
