#!/bin/bash
set -eou pipefail

. ../utils.sh

if [[ "$(docker ps | grep conjur-cli)" != "" ]]; then
  docker stop conjur-cli
  docker rm conjur-cli
fi

oc login -u $OSHIFT_CLUSTER_ADMIN
oc project default

if has_project $CONJUR_PROJECT_NAME; then
  oc delete project $CONJUR_PROJECT_NAME

  printf "Waiting for $CONJUR_PROJECT_NAME project deletion to complete"

  while : ; do
    printf "..."
    
    if has_project "$CONJUR_PROJECT_NAME"; then
      sleep 5
    else
      break
    fi
  done

  echo ""
fi

echo "Conjur environment purged."
