#!/bin/bash -x
set -eou pipefail

./0_check_dependencies.sh
./stop

oshift="${OSHIFT_CONJUR_ADMIN:-unset}"
if [[ $oshift != unset ]]; then
  ./1_create_openshift_project.sh
fi
./2_build_and_push_containers.sh
./3_deploy_master.sh
./4_print_config.sh
