#!/bin/bash 
set -eou pipefail

./0_check_dependencies.sh
./stop
./1_create_openshift_project.sh
./2_build_and_push_containers.sh
if [[ $CONJUR_SIMPLE_CLUSTER == true ]]; then
  ./3_deploy_simple_cluster.sh
else
  ./3_deploy_master_cluster.sh
fi
./4_print_config.sh
