#!/bin/bash
set -eou pipefail

. ../utils.sh

if [[ "$(docker ps -a | grep conjur-master)" != "" ]]; then
  docker stop conjur-master
  docker rm conjur-master
fi

conjur_nodes=$(docker ps -a -f "label=role=conjur_node" --format "{{ .Names }}")
for i in $conjur_nodes; do
  docker stop $i
  docker rm $i
done

if [[ "$(docker ps -a | grep conjur-cli)" != "" ]]; then
  docker stop conjur-cli
  docker rm conjur-cli
fi

if [[ "$(docker network list | grep conjur-master-network)" != "" ]]; then
  sleep 2
  docker network rm conjur-master-network
fi

scope stop

echo "Conjur environment purged."
