#!/bin/bash 

DEMO_CLIENT=demo-client

echo "Starting demo container..."
docker run -d \
  -v $(pwd)/demo:/demo \
  --entrypoint sh \
  --name $DEMO_CLIENT \
  --env CONJUR_APPLIANCE_URL=https://$CONJUR_MASTER_HOSTNAME:$CONJUR_MASTER_PORT/api \
  --env CONJUR_MASTER_HOSTNAME=$CONJUR_MASTER_HOSTNAME \
  --env CONJUR_MASTER_HOST_IP=$CONJUR_MASTER_HOST_IP \
  --env CONJUR_MASTER_PORT=$CONJUR_MASTER_PORT \
  --env CONJUR_ACCOUNT=$CONJUR_ACCOUNT \
  cyberark/conjur-cli:4-latest \
  -c "sleep infinity"
sleep 2
# use in lieu of volume mount
#docker cp ./demo $DEMO_CLIENT:/demo
clear
echo "cd to /demo and run scripts in sequence"
docker exec -it $DEMO_CLIENT bash
echo "Deleting demo container..."
docker stop $DEMO_CLIENT
sleep 2
docker rm $DEMO_CLIENT
