version: "2"

networks:
  demo:
  bridge:

services:
  demo-pg:
    image: postgres:9.3
    ports: [ "35432:5432" ]
    networks:
      - demo

  hello:
    build: .
    image: hello:demo
    ports: [ "8080:8080" ]
    container_name: hello
    environment:
      CONJUR_VERSION: "5"
      CONJUR_APPLIANCE_URL: https://$CONJUR_MASTER_HOST_NAME:$CONJUR_MASTER_PORT
      CONJUR_CERT_FILE: /etc/conjur-$CONJUR_ACCOUNT.pem
      CONJUR_ACCOUNT: $CONJUR_ACCOUNT
      CONJUR_AUTHN_LOGIN: $CONJUR_AUTHN_LOGIN
      CONJUR_AUTHN_API_KEY: $CONJUR_AUTHN_API_KEY
    volumes:
      - ./secrets.yml:/etc/secrets.yml
      - ./target:/target
    command: [ "sleep", "2000000" ]
#    command: [ "java", "-jar", "./target/hello-0.1.0.jar" ]
    networks:
      - demo
      - bridge
