#!/bin/bash
source lib/util

begin "Cleaning up any existing docker compose state"
{
  if [[ "$DOCKER_HOST" != "" ]]; then
    echo "Source unset_docker.env to use local docker daemon"
    exit -1
  fi
  docker-compose rm -fs
} &>/dev/null
finish
