---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  type: LoadBalancer
  selector:
    app: conjur-follower
  ports:
  - port: 443
    name: https
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: conjur-follower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-follower
        name: conjur-follower
        role: follower
    spec:
      containers:
      - name: conjur-appliance
        image: {{ CONJUR_APPLIANCE_IMAGE }}
        imagePullPolicy: Always
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/dev
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
