version: "2"

networks:
  demo:

services:
  demo-pg:
    image: postgres:9.3
    ports: [ "5432:5432" ]
    networks:
      - demo

  hello:
    build: .
    ports: [ "8080:8080" ]
    environment:
      CONJUR_APPLIANCE_URL: http://conjur-master:30443
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - ./secrets.yml:/etc/secrets.yml
      - ./target:/target
    command: [ "java", "-jar", "/target/hello-0.1.0.jar" ]
