#!/bin/bash 
docker-compose up -d
docker exec -itu root jenkins-master bash -c "echo \"$CONJUR_MASTER_HOST_IP	$CONJUR_MASTER_HOST_NAME\" >> /etc/hosts"
echo "cd to /demo and run scripts in order"
docker exec -itu root jenkins-master bash
