#!/bin/bash
set -eou pipefail

./0_check_dependencies.sh
./stop
./1_create_openshift_project.sh

./2_build_and_push_containers.sh
./3_deploy_master.sh
./4_deploy_admin_cli.sh
#./5_init_cluster.sh
#./6_configure_standbys.sh
#./7_deploy_followers.sh
./8_print_config.sh
